name: Compile and Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  compile-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: 'paper.tex'
          post_compile: "mv *.pdf public"
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
